name: CI

on:
  push:
  pull_request:

jobs:
  release:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build
        run: go build ./cfgloader
      - name: Test
        run: go test ./cfgloader
